[project]
name = "levelup"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "datasets>=3.6.0",
]

[build-system]
requires = ["uv>=0.1.36"]
build-backend = "uv.buildapi"
